### ISSUE TITLE
ESM Module CLI Warning

### ISSUE THREAD

**Issue by jamesikanos** [nodeca/image-blob-reduce#13]
Great library. But, the Angular CLI gives a warning related to CommonJS.

```
WARNING in /...REDACTED...dia-input.component.ts depends on 'image-blob-reduce'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
I'm importing as:
```
import imageReducer from 'image-blob-reduce';
import pica from 'pica';
```

If I change the import to `import imageReducer from 'image-blob-reduce/dist/image-blob-reduce.min.js'` then my bundle size increases by 20kb (but the warning goes away).

It works either way so this is not a high priority.

**Comment by puzrin** [comment]
As far as i understand, angular gives you link how to dim that warning. So, nothing to fix in this repo.

```
import imageReducer from 'image-blob-reduce';
import pica from 'pica';
```

Do you really need direct access to pica? If yes, try bundled one from `image-blob-reduce`:

```
import ImageReducer from 'image-blob-reduce';
const pica = ImageReducer.pica;
```

**Comment by jamesikanos** [comment]
I understand, but I don't want to simply "dim" the warning. I'm not really a "node module expert" so don't really know how easy/hard it is to convert your module to an ES module.

This module is the only one in my application that produces the error.

As I said, it isn't a really high priority (as I can dim the warning).

ps. Thanks for the tip on using bundled pica. I've made that change.

**Comment by puzrin** [comment]
Sorry, there are no plans to change this module to es6
