### ISSUE TITLE
Detect auto-rotation

### ISSUE THREAD

**Issue by sandstrom** [nodeca/image-blob-reduce#15]
Not sure if this issue is relevant to your library. So this may be a non-issue.

But we've ran into a problem where the image loaded from an <img> element would be rotated by the browser based on EXIF data.

We found a solution to this in another library:
https://github.com/blueimp/JavaScript-Load-Image/blob/v3.0.0/js/load-image-orientation.js#L37-L53

Just wanted to share this code with you, in case you run into the same problem.

I've used pica for a while and are very happy. Thanks for a great library! 🏅 

```js
/**
 * Determine if the browser defaults to auto-rotating images based on EXIF orientation when
 * loading images into an <img> element (e.g. when using the web API method `Image`).
 *
 * This neat trick is inspired by:
 * https://github.com/blueimp/JavaScript-Load-Image/blob/v3.0.0/js/load-image-orientation.js#L37-L53
 * (versions >3.0 take even more issues into account, but we don't need that)
 *
 * The image data consists of a black 2px wide, 1px tall JPEG with the following meta information set:
 * - EXIF orientation: 6 (camera rotated 90° CW)
 *
 * @return {Promise} Resolves with `true` if HTML images are auto-rotated
 */
let determineAutoRotation = function() {
  if (!autoRotationPromise) {
    autoRotationPromise = new Promise((resolve, reject) => {
      let img = document.createElement('img');
      let rotatedImageUrl = 'data:image/jpeg;base64,/9j/4QAiRXhpZgAATU0AKgAAAAgAAQ' +
        'ESAAMAAAABAAYAAAAAAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE' +
        'BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
        'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIAAEAAgMBEQACE' +
        'QEDEQH/xABKAAEAAAAAAAAAAAAAAAAAAAALEAEAAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAA' +
        'AAAAAAAAAAEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwA/8H//2Q==';

      img.onload = function() {
        // `true` if image is rotated according to EXIF orientation
        resolve(img.width === 1 && img.height === 2);
      };

      img.onerror = function() {
        reject(new Error('Determining image auto-rotation failed'));
      };

      img.src = rotatedImageUrl;
    });
  }

  return autoRotationPromise;
};
```

**Comment by puzrin** [comment]
See this https://github.com/nodeca/image-blob-reduce/blob/master/lib/jpeg_plugins.js.

This library works different. It creates cloned blob wihout orienation. Then resize, apply orienaion and atach original headers except profile.

**Comment by sandstrom** [comment]
Alright, maybe it won't occur here. But as I understood it this issue exist anytime you're reading from an <img> element, which I thought this library does.

https://github.com/w3c/csswg-drafts/issues/4666#issuecomment-610962845
https://github.com/blueimp/JavaScript-Load-Image/issues/97

Anyway, you know this better so I'll trust you. And if you do run into this in the future maybe this can serve as good starting point.

Cheer! 😄

**Comment by puzrin** [comment]
Thanks for good intent and shared code :+1: .

It's not said explicit in readme, this lib was created exactly after chrome started to rotate images :). But i will be grateful for code review and notes from anyone who has experience in this area. Because i'm not frontend dev and don't track latest state of browsers specifics.
