### ISSUE TITLE
Error when used in create-react-app build (but not development)

### ISSUE THREAD

**Issue by danielbrauer** [nodeca/image-blob-reduce#17]
I'm pretty new to web development, so I'm not sure if this is something you can help with. I'm getting an error of the form:

```
ReferenceError: o is not defined
    at e (blob:http://localhost:5000/2bdae74b-66c2-443f-8a8f-6b18edc7fb4c:1:313)
    at blob:http://localhost:5000/2bdae74b-66c2-443f-8a8f-6b18edc7fb4c:1:352
```

The stack trace is all minified, but the top looks like this:

```
e (2bdae74b-66c2-443f-8a8f-6b18edc7fb4c:formatted:23)
(anonymous) (2bdae74b-66c2-443f-8a8f-6b18edc7fb4c:formatted:27)
Worker Created (async)
t.exports (image-blob-reduce.esm.mjs:1613)
w (image-blob-reduce.esm.mjs:1689)
n.acquire (image-blob-reduce.esm.mjs:575)
(anonymous) (image-blob-reduce.esm.mjs:1933)
(anonymous) (image-blob-reduce.esm.mjs:1932)
Promise.then (async)
(anonymous) (image-blob-reduce.esm.mjs:1930)
(anonymous) (image-blob-reduce.esm.mjs:2016)
```

Is this expected to work with Create React App? Why might it be failing only in a production build? As far as I can tell, everything is fine until I get to a call to `toBlob()`.

**Comment by puzrin** [comment]
Sorry, no ideas, i don't use react an not familiar with it's bundler.

**Comment by danigb** [comment]
I have the same issue... My guess is there are some JS error that is ignored... until you run the minifier.

**Comment by puzrin** [comment]
@danigb https://github.com/nodeca/pica/blob/master/package.json#L12 that issue is not actual if you use last version.

**Comment by danigb** [comment]
I'm using latest version...

**Comment by puzrin** [comment]
I'd recommend to recheck files on your disk, is it really latest as you think.

If really yes - then probably you need report error to bundler's tracker, why it works not as expected. It MUST use file from `dist/`, as pointed in 'main'.

**Comment by sudhanshu16** [comment]
@danigb any update regarding this? I am facing the same issue. Any help will be appreciated.

**Comment by hurda21** [comment]
@sudhanshu16 I'm using Angular, but I ran into a very similar bug (not in development). I got it working by overriding the pica object inside the reducer object with my own that I imported directly from pica. Strange because both are listed as using the latest version (6.1.1 as of today), so @danielbrauer @puzrin there is something weird going on here with the default dependencies.

**Comment by cmdcolin** [comment]
I had a problem where it looked like this in production

```
200a1799-9a4c-43ac-ab95-be009946c398:1 Uncaught ReferenceError: i is not defined
    at e (200a1799-9a4c-43ac-ab95-be009946c398:1)
    at 200a1799-9a4c-43ac-ab95-be009946c398:1
e @ 200a1799-9a4c-43ac-ab95-be009946c398:1
(anonymous) @ 200a1799-9a4c-43ac-ab95-be009946c398:1
d1fe213f-35a4-4d4f-883d-072f9df72b55:1 Uncaught ReferenceError: i is not defined
    at e (d1fe213f-35a4-4d4f-883d-072f9df72b55:1)
    at d1fe213f-35a4-4d4f-883d-072f9df72b55:1
e @ d1fe213f-35a4-4d4f-883d-072f9df72b55:1
(anonymous) @ d1fe213f-35a4-4d4f-883d-072f9df72b55:1
f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1 Uncaught ReferenceError: i is not defined
    at e (f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1)
    at f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
e @ f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
(anonymous) @ f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1 Uncaught ReferenceError: i is not defined
    at e (c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1)
    at c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
e @ c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
(anonymous) @ c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
```

I realized it is probably because create-react-app webpack configs doesn't have great webworker support (have to use worker-loader and rewire or other crazy stuff)

I fixed by turning off the webworker option in the pica instance that we pass to the ImageBlobReduce constructor

```

//@ts-ignore
import ImageBlobReduce from "image-blob-reduce";
//@ts-ignore
import Pica from "pica";

const pica = Pica({ features: ["js", "wasm", "cib"] });
const reduce = new ImageBlobReduce({ pica });


```

**Comment by puzrin** [comment]
See https://github.com/nodeca/image-blob-reduce#known-issues

**Comment by pyliu** [comment]
> I had a problem where it looked like this in production
> 
> ```
> 200a1799-9a4c-43ac-ab95-be009946c398:1 Uncaught ReferenceError: i is not defined
>     at e (200a1799-9a4c-43ac-ab95-be009946c398:1)
>     at 200a1799-9a4c-43ac-ab95-be009946c398:1
> e @ 200a1799-9a4c-43ac-ab95-be009946c398:1
> (anonymous) @ 200a1799-9a4c-43ac-ab95-be009946c398:1
> d1fe213f-35a4-4d4f-883d-072f9df72b55:1 Uncaught ReferenceError: i is not defined
>     at e (d1fe213f-35a4-4d4f-883d-072f9df72b55:1)
>     at d1fe213f-35a4-4d4f-883d-072f9df72b55:1
> e @ d1fe213f-35a4-4d4f-883d-072f9df72b55:1
> (anonymous) @ d1fe213f-35a4-4d4f-883d-072f9df72b55:1
> f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1 Uncaught ReferenceError: i is not defined
>     at e (f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1)
>     at f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
> e @ f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
> (anonymous) @ f5e4d2fb-8d00-49ba-839d-20318c4a2aff:1
> c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1 Uncaught ReferenceError: i is not defined
>     at e (c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1)
>     at c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
> e @ c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
> (anonymous) @ c61c2004-99b9-4aa4-9e2e-ae247d84ec4b:1
> ```
> 
> I realized it is probably because create-react-app webpack configs doesn't have great webworker support (have to use worker-loader and rewire or other crazy stuff)
> 
> I fixed by turning off the webworker option in the pica instance that we pass to the ImageBlobReduce constructor
> 
> ```
> 
> //@ts-ignore
> import ImageBlobReduce from "image-blob-reduce";
> //@ts-ignore
> import Pica from "pica";
> 
> const pica = Pica({ features: ["js", "wasm", "cib"] });
> const reduce = new ImageBlobReduce({ pica });
> ```

this solved my issue, thanks for the code snippet 😃

**Comment by chaudev** [comment]
I use nextjs 14, this worked for me

```javascript
import ImageBlobReduce from "image-blob-reduce";
import Pica from "pica";

const pica = Pica({ features: ["js", "wasm", "cib"] });
const reduce = new ImageBlobReduce({ pica });
```
