### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by AfiqRosli** [nodeca/image-blob-reduce#18]
I'm developing an app using Vue.js 2 and I'm including the `const reduce = require('image-blob-reduce')()` in a View component. Page didn't load and consoled out an error (Uncaught TypeError: __webpack_require__(...) is not a function).

Tried removing the `()` in `require('image-blob-reduce')()` and when it hits the `reduce.toBlob function` (refer to the function below), it gives an error saying **reduce.toBlob is not a function** .

```
// The function
reduce.toBlob(file, { max: 1000 }).then(blob => {
          console.log(blob)
})
```

I'm not familiar with webpack and I don't have any webpack configuration file. There are `babel.config.js` and `vue.config.js`. Not sure if anything needs to be added within these files or if I'm required to create a `webpack.config.js `.

Would appreciate it if anyone could help me with this issue.

**Comment by puzrin** [comment]
Generic programming questions are out of scope.

**Comment by johnbonds** [comment]
I'm having the same issue. LMK if you figure it out and I'll do the same.

**Comment by johnbonds** [comment]
The solution I came up with is:

import ImageBlobReduce from 'image-blob-reduce';
const reduce = new ImageBlobReduce();

Then you can call it normally.
