### ISSUE TITLE
Demo page shows error on load: Uncaught TypeError: require$$0 is not a constructor

### ISSUE THREAD

**Issue by panabee** [nodeca/image-blob-reduce#20]
Thanks for creating this awesome software.

In Chrome, load https://nodeca.github.io/image-blob-reduce/

The JavaScript console shows this error: 

```
Uncaught TypeError: require$$0 is not a constructor
    at index.js:3350
    at index.js:3376
```

**Comment by puzrin** [comment]
Thanks. Fixed.

**Comment by panabee** [comment]
Thanks for the fast response!
