### ISSUE TITLE
Using minified file ImageBlobReduce is not correctly instantiated

### ISSUE THREAD

**Issue by gmzu** [nodeca/image-blob-reduce#21]
Using minified file, window.ImageBlobReduce() is not usable.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3656980/103464835-20935a80-4d37-11eb-89b7-bfea35192479.png">

name & prototype are wrong.
No problem with unminified file.

**Comment by puzrin** [comment]
What's exactly wrong? I don't understand.

**Comment by gmzu** [comment]
I created two jsbin to reproduce the issue

First jsbin using uniminified file: all ok
[JS Bin 1](https://jsbin.com/yiyonoxaze/2/edit?html,js,console,output)

Second jsbin using minified file: error
[JS Bin 2](https://jsbin.com/dapofixake/1/edit?html,console,output)

**Comment by puzrin** [comment]
Hm... I've updated local demo to use dist files, and problem is with webworkers mode.

This works:

```js
var reducer = new window.ImageBlobReduce({
  pica: window.ImageBlobReduce.pica({ features: [ 'js', 'wasm' ] })
});
```

This NOT works:

```js
// the same as new window.ImageBlobReduce()
var reducer = new window.ImageBlobReduce({
  pica: window.ImageBlobReduce.pica({ features: [ 'js', 'wasm', 'ww' ] })
});
```

Seems terser breaks something in pica build (it's built with browserify + webforkify and create webworker on the fly) https://github.com/nodeca/pica/tree/master/dist

**Comment by puzrin** [comment]
With terser options 

```
	{
      mangle: false,
      compress: true,
      format: {
        comments: 'all',
        beautify: true,
        indent_level: 2
      }
    }
```

Error is:

```
ReferenceError: commonjsRequire is not defined b487d00f-a624-47ac-8138-1e1bacf9db6e:19:22
```

**Comment by rlidwka** [comment]
Minified file in this library should be compiled with `terser({ compress: { evaluate: false } })` option for terser [here](https://github.com/nodeca/image-blob-reduce/blob/b74f90d925dc656e36e4bb2e1aa17c4f68f9212a/support/rollup.config.js#L20).

The problem right now is that terser eliminates `typeof commonjsRequire` check completely from [here](https://github.com/nodeca/image-blob-reduce/blob/b74f90d925dc656e36e4bb2e1aa17c4f68f9212a/dist/image-blob-reduce.js#L77).

**Comment by puzrin** [comment]
Ref https://github.com/terser/terser/issues/837#issuecomment-758177671

**Comment by puzrin** [comment]
Fixed minified build & added info for outer calls https://github.com/nodeca/image-blob-reduce#known-issues
