### ISSUE TITLE
gif converted to png

### ISSUE THREAD

**Issue by jam33** [nodeca/image-blob-reduce#22]
processing a jpg results in a jpg. 
processing a png results in a png.

However, processing a gif results in a png.  According to both mime checks on the server and checking the resultant file with IrfanView.

Is there a way to prevent this from happening?  If not, what is the benefit for the why the conversion should occur?  It's actually increasing my file size.

Thanks!

**Comment by jam33** [comment]
seems like it's a limitation of the browsers.  pica looks to call "canvas.toBlob" and it seems like most major browsers export PNG even when told to export GIF.

You can see the results of each file type by visiting..
[http://kangax.github.io/jstests/toDataUrl_mime_type_test/](url)

if you agree, it might be worth mentioning on the documentation that gif isn't exportable.  i realize it is not your fault, but might help future users.

thanks!

**Comment by puzrin** [comment]
I'd say, this package is not magical, and is expected to be use only with compessible sources - jpg. For the rest result will be not predicable.

> if you agree, it might be worth mentioning on the documentation that gif isn't exportable. i realize it is not your fault, but might help future users.

PR welcome, but keep in mind, this is NOT just "gif problem", i wold not recommend use this package for png to. Only for jpeg.

**Comment by jam33** [comment]
while it might not be magical, it is still very very impressive and useful!  so thank you for your hard work!

i agree with what you said and that most scaling would occur on jpg's.  it does a fantastic job at that (output is very high quality).  

i'll probably just add client side code to skip resizing of gif's and png's and then check my server logs after a few months to see if users are actually uploading large gif/png files.  it likely won't be a big issue.

thanks!

**Comment by puzrin** [comment]
On server you could use https://github.com/lovell/sharp for the rest.
