### ISSUE TITLE
Could not find a declaration file for module 'image-blob-reduce'

### ISSUE THREAD

**Issue by karinaespinola** [nodeca/image-blob-reduce#23]
I get this error when trying to use the module. Here's my code:

```
const reduce = require('image-blob-reduce');

export async function reduceBlob(originalBlob) {
  await reduce
  .toBlob(originalBlob, { max: 300 })
  .then(blob => { 
    console.log(blob);
    return blob;
  });
}
```

Not sure how to solve this issue :P 

Thank you!

**Comment by puzrin** [comment]
Sorry, can't help with typescript.

**Comment by zauni** [comment]
@karinaespinola You have to create a file `image-blob-reduce.d.ts` with this content:

```typescript
declare module 'image-blob-reduce';
```

If the TS compiler is complaining even with this file, you have to adjust your `tsconfig.json`. So in your "compilerOptions" object you have to add a paths object like this:

```json
{
  "compilerOptions": {
    "paths": {
      "*": ["*", "your/path/to/the/folder/with/the/new/file/*"]
    }
  }
}
```

**Comment by karinaespinola** [comment]
Thank you, @zauni I will test your solution :) I eventually found a workaround and  I didn't use this module, but I will give it a try.

Thanks!

**Comment by melnikovdv** [comment]
I made a bit more sophisticated module. 

At first install `npm install --save @types/pica` to get types for reduce options. 

Then add `image-blob-reduce.d.ts` to your project with such content: 

```typescript
declare module 'image-blob-reduce' {
    import { PicaResizeOptions } from "pica";
    namespace ImageBlobReduce {
        interface ImageBlobReduce {
            toBlob(file: File, options: ImageBlobReduceOptions): Promise<Blob>;
        }

        interface ImageBlobReduceStatic {
            new(options?: any): ImageBlobReduce;

            (options?: any): ImageBlobReduce;
        }

        interface ImageBlobReduceOptions extends PicaResizeOptions {
            max: number;
        }
    }
    const reduce: ImageBlobReduce.ImageBlobReduceStatic;
    export = reduce;
}

```

If you need other methods except `toBlob()` add them to `ImageBlobReduce` interface. 

Hey @puzrin, If it seems ok to you I can try to add @types for this library. Have never done it before, but it shouldn't be very difficult.

**Comment by puzrin** [comment]
@melnikovdv 

> Hey @puzrin, If it seems ok to you I can try to add [@types](https://github.com/DefinitelyTyped/DefinitelyTyped) for this library. Have never done it before, but it shouldn't be very difficult.

If that does not depends on me, you don't need my opinion :). I don't use TS, do as you wish/need.
