### ISSUE TITLE
Bug in scaling logic example in documentation

### ISSUE THREAD

**Issue by tomdav999** [nodeca/image-blob-reduce#24]
Hi, thanks for this amazing library.  I was having some problems using the example provided in the documentation to change scaling logic.  After looking at the actual function I finally got it to work after adding `return Promise.resolve(env);` at the end of the function.   I would recommend updating the documentation.
```
reducer._calculate_size = function (env) {
.
.
.
	return Promise.resolve(env);
};
```

**Comment by puzrin** [comment]
Thanks for report! I guess simple `return env;` should be ok?

**Comment by tomdav999** [comment]
Honestly I don't know.  I just copied the code from the actual function includes the following lines: 

```
// Info for user plugins, to check if scaling applied
  env.scale_factor = scale_factor;

  return Promise.resolve(env);
};
```
