### ISSUE TITLE
mozjpeg encoding

### ISSUE THREAD

**Issue by tomdav999** [nodeca/image-blob-reduce#25]
Thanks again for this very useful library.  Just wondering if there is a way to encode output as mozjpeg to further reduce size without having to resort to another utility (with additional jpeg compression).  Currently I am saving output as high jpeg quality (somewhat defeats purpose of blob reduce) > uploading to server > recompress with mozjpeg.  It would be great if this could be done in pica during the blob > jpeg transformation (or with blob > mozjpeg javascript library).

**Comment by puzrin** [comment]
JS has no mozjpeg interface. This can't be done in browser for free. You could assemble mozjpeg to webassembly with emscripten, but that's out of this project scope.

**Comment by tomdav999** [comment]
Thanks for the quick reply.  I noticed this site compresses images in-browser with mozjpeg and impressively fast:

https://mozjpeg.com/

Perhaps they are doing something more complicated than it seems.  Oh well, I guess I will stick with server side compression after upload.

**Comment by puzrin** [comment]
- https://github.com/lvgl/lv_font_conv
- https://github.com/fontello/wawoff2

I have experience with building C libs for browser. It's not a big deal. First project contains FreeType, second - woff2. Problem is those files have notable size, and that's a bit out if this project scope. This project goal is to have something small & smart, to significantly reduce traffic and post-processing CPU consumption (on server side). IMO it does it's job well.

**Comment by tomdav999** [comment]
One of the big issues I am running into with in browser jpeg encoding is the chroma sampling.  It seems browsers aggressively subsample chroma no matter what the quality!  This makes it pretty much impossible to resize file uploads in browser and preserve chroma.  With mozjpeg the options are exposed so you can disable chroma sampling.  I found some wasm that seem to do in browser mozjpeg copression pretty fast, for example, note this demo (with Trellis quantisation loop set to 1 for fastest encoding):

https://3bl3gamer.github.io/wasm-mozjpeg/examples/settings/

**Comment by puzrin** [comment]
pica (behind this package) uses canvas to extract image bitmap. That leaves only 8bits per channel. It's the known limitation and this package is not recommended for highest quality images resize.

**Comment by tomdav999** [comment]
Isn't jpeg 8 bits?  If so, not sure I understand the issue of using pica to resize jpegs?

**Comment by puzrin** [comment]
jpeg is 8 bits, but uses gamma correction (non linear) to increase resolution of dark tones. After transfer to canvas, RGBA seems linear. That causes information loss.

For best result, specific to jpeg, it should bi unpacked to 16bits. But that's completely different complexity, out of package scope.
