### ISSUE TITLE
Add example to use ES6 Import

### ISSUE THREAD

**Issue by adarshmadrecha** [nodeca/image-blob-reduce#30]
Currently the docs (readme.md) uses the below example
```js
const reduce = require('image-blob-reduce')();
```

It would be awesome if you could add document on how to use the same when using ES6 Module
```js
// Something like this (Not sure if this is the right way to do)
import Reduce from "image-blob-reduce"
const reduce = Reduce()
````

**Comment by puzrin** [comment]
IMO this is related to basic programming questions and such things are out of this package scope. You can try to propose PR, but i don't give guarantee of merge.
