### ISSUE TITLE
Chrome image is black , works fine on Safari 

### ISSUE THREAD

**Issue by adamgins** [nodeca/image-blob-reduce#31]
Hi,

I am using Chrome Version 93.0.4577.82 (Official Build) (x86_64) on OSX 11.6 

<img width="745" alt="Screen Shot 2021-09-21 at 5 44 25 pm" src="https://user-images.githubusercontent.com/7233741/134132475-00a47f98-9b07-4eef-93ac-cca4b201cc65.png">
d 

The same image in Safari works fine. Any ideas. I have had others hit it with what seems to be the same  version of chrome and it works for them.

could there be some security setting on my machine that causes this?

thanks

**Comment by puzrin** [comment]
Do you see any error in debug console? On FF one user had problems due activated "fingerprint protection".

**Comment by adamgins** [comment]
Thanks for the quick response. 

Nothing on console :-/ 

I downloaded Chrome Beta and it works fine. Also updated my Safari and works fine with both previous and current version. So it seems very specific to this version of Chrome and on my machine.

**Comment by jinevo** [comment]
Hello,
I'm facing the same bug since Chrome 94.(Version 94.0.4606.61 (Official build) (arm64)) Only PNG file seem to work.

**Comment by adamgins** [comment]
I could not get it to work.. ended up installing a Chrome Beta to get around it.

**Comment by jinevo** [comment]
Indeed, with Chrome 95 (beta), there is not the error.

**Comment by rschuil** [comment]
Related: https://github.com/nodeca/pica/issues/203

**Comment by rschuil** [comment]
Adding "alpha: true" to config solved the problem for me.

**Comment by puzrin** [comment]
Try v4.1, it uses pica v9, which does not have `.alpha` option anymore (canvas transparency is always on).

Also, as far as i see, actual chrome version is more high than been reported about problem.

**Comment by adamgins** [comment]
FYI I upgraded chrome to Version 96.0.4664.93 (Official Build) (x86_64) and it now seems to be working
it was always working for me with Chrome beta, it was the previous version that was borked for me
