### ISSUE TITLE
Uncaught ReferenceError: sp is not defined

### ISSUE THREAD

**Issue by osnysantos** [nodeca/image-blob-reduce#32]
It's working locally but after deploying to production I'm getting this exception when trying to `await reduce.toBlob(file, { max: 1000 });`.

I'm using Chrome on Macbook pro.

**Comment by puzrin** [comment]
IMO that's issue about your bundler, not about this package.

**Comment by osnysantos** [comment]
It started exactly when I added the library. Do you know what could be causing it in terms of deployment? I'm using Netlify as a host

**Comment by puzrin** [comment]
1. https://github.com/nodeca/image-blob-reduce#known-issues
2. If you report issue, you are expected to provide simple & reproducible proof, narrowed to this package only.

**Comment by rscotten** [comment]
@osnysantos @puzrin I have this same problem.  It works locally but when I build/deploy using NextJS, I get this Uncaught ReferenceError.

**Comment by rscotten** [comment]
This fixed it for me: https://github.com/nodeca/image-blob-reduce/issues/17#issuecomment-751550135

I've never seen a package work in development and not work in production before.  Weird.

**Comment by puzrin** [comment]
@rscotten the ordinary difference between dev/prod is different minifier options. People wish to save assets size on production, but don't like to wait on dev when multiple rebuilds happen on every change.

Some very aggressive options can change struct of wrapper, and that breaks creating source string for webworker. That's generic answer, and those webpack/terser options are known. But i don't know specific answer for `create-react-app` (how to tune it).
