### ISSUE TITLE
Black line with big images

### ISSUE THREAD

**Issue by vicsanca** [nodeca/image-blob-reduce#35]
Hello

Reducing some big images to not so big (but still big images) a black line appears in the resized image.

To reproduce try {max:2880, unsharpAmount: 80, unsharpRadius: 0.6, unsharpThreshold: 2 } with this image:

Downsizing to max:4096 already shows a black line, but in different place.

https://imagecompression.info/test_images/
RGB 16 bits set, big_building or big_tree images.

Thanks

**Comment by puzrin** [comment]
Please, create instruction, how to reproduce with minimal efforts.

- Via existing demo, if possible https://nodeca.github.io/image-blob-reduce/
- Or via test repo, with minimal code (to clone & open in single click)

Also need info about browser/OS.

**Comment by vicsanca** [comment]
Yes, use one of the images inside this zip: https://idieikon-my.sharepoint.com/:u:/p/vicsanca/ERyK7TLvLcJKuhomQ4cgBJcBerdHtoqtBqEON7_X68aKvA?e=VbQBZJ
Use in your demo page this values:
{max:2880, unsharpAmount: 80, unsharpRadius: 0.6, unsharpThreshold: 2 }

Thanks

**Comment by puzrin** [comment]
Don't see problem here https://nodeca.github.io/image-blob-reduce/

I'm a bit busy with other things, no room to search how to reproduce. Could you create a test repo, usable to just clone and open html page in single click to see problem? + browser info + sample scereenshot where to see.

**Comment by vicsanca** [comment]
Hello again.

Sorry, unable to reproduce again...that day was very easy to reproduce but impossible today, maybe was a browser (Edge Chromium) bug. I will let you know if I'm able to reproduce again.

Thanks and sorry
