### ISSUE TITLE
Web worker compatibility

### ISSUE THREAD

**Issue by IrregularShed** [nodeca/image-blob-reduce#37]
I would like to be able to process large batches of images - maybe as many as 100 - using a web worker script,  so that I don't tie up the UI thread. When I tried, I discovered that this library uses some DOM features (creating an `<img>`) and APIs (eg `window.URL`) that there's no way of using with a worker.

I wanted to use this library rather than pica so that the metadata would be retained, as it's extremely useful for the use case (a PWA for engineers doing kitchen appliance fittings - they have to take photos during their work). Before I try and implement something myself, do you know of any way to achieve what I'm trying to do without rewriting most of it?

**Comment by puzrin** [comment]
This is wrapper around pica. It will use WW automatically when available (inside of pica)
