### ISSUE TITLE
Add min to options

### ISSUE THREAD

**Issue by tanmuhittin** [nodeca/image-blob-reduce#4]
In my case I need 300px x 300px square images. So after resizing, I cut the images to 300px x 300px.

If I cut the image to square before resizing It consumes a lot of ram. So I prefer cutting after resize operation.

For this purpose I need short edge to be 300px. So, in such case min option is needed.

After some digging I found that it must be added to _transform function : https://github.com/nodeca/image-blob-reduce/blob/3e147f37500ebecbb855d01efa0019ec28e02248/index.js#L115

**Comment by puzrin** [comment]
Thanks for suggestion. I did not decided yet, how much should exist in default api. Still need decide, should we have option to pass blob intact if size is not changed. Let's keep this open for a while.

Note, you could override `_transform()` method of instance. With new 1.0.3 release this is very simple (code size reduced).

https://github.com/nodeca/image-blob-reduce/blob/c51397151807e70db3fdf83d4adbb1ffa8eeda77/index.js#L115-L134

Package is specially designed to simplify customizations.

**Comment by tanmuhittin** [comment]
Thanks :) I override the method as you described. It works 👍

**Comment by puzrin** [comment]
At first glance, `min` option will not cover all possible cases. For example, 1x1000000px image will not be reduced and many ppl could wish different behaviour. This is opinion-based & app-specific - can not be landed as simple option.

I'd suggest to [optionally] extend readme [samples](https://github.com/nodeca/image-blob-reduce#customization), an close his issue.

**Comment by puzrin** [comment]
https://github.com/nodeca/image-blob-reduce/commit/9f148616d91a4be333980c1be1004414a89b2275

Closing. Readme sample should be enougth.
