### ISSUE TITLE
slow image resizing

### ISSUE THREAD

**Issue by stefanhoelzl** [nodeca/image-blob-reduce#40]
Hello,

I am trying to use `image-blob-reduce` to create thumbnails by resizing input images.
But I discovered that it takes very long to resize images (up to 2 seconds for ~4MB jpeg)

This is the code I use for testing
```javascript
var reducer = new window.ImageBlobReduce();

fetch("https://images.pexels.com/photos/1670187/pexels-photo-1670187.jpeg?fm=jpg&w=3840&h=5760")
  .then(function (response) {
    return response.blob();
  })
  .then(function (blob) {
    var start = window.performance.now();
    reducer
      .toBlob(blob, {max: 500})
      .then(function (blob) {
        console.log(window.performance.now() - start);
      });
  });
```
https://jsfiddle.net/c46uz3hp/

Running this takes around 1.6seconds (up to 2seconds), I have tested this on a MacBook Pro (`2,5 GHz Dual-Core Intel Core i5`) with Safari and Chrome.

Are these times expected? It seems very slow to me.
Any advice on how I can improve this?

Thank you!

**Comment by puzrin** [comment]
> Are these times expected? It seems very slow to me.

Seems expected for desired quality demands.

> Any advice on how I can improve this?

Use native canvas resize, then replace result with pica on ready.
