### ISSUE TITLE
UI is blocking on Safari

### ISSUE THREAD

**Issue by stefanhoelzl** [nodeca/image-blob-reduce#41]
Hello,

on Safari (`Version 15.4 (15613.1.17.1.13, 15613)`) the UI is blocked when using `image-blob-reduce`.
Here is some example code to reproduce 
```javascript
var reducer = new window.ImageBlobReduce();

function imageBlobReduce() {
  console.log("start")
  fetch("https://images.pexels.com/photos/1670187/pexels-photo-1670187.jpeg?fm=jpg&w=3840&h=5760")
    .then(function (response) {
      return response.blob();
    })
    .then(function (blob) {
      return reducer.toBlob(blob, {max: 500});
    })
    .then(() => console.log("done"));
}
```

```html
<body onload="imageBlobReduce()">
  <img 
    width="100px" 
    src="https://i.stack.imgur.com/kOnzy.gif"
  />
</body>
```
[jsfiddle](https://jsfiddle.net/qwbs9gvu/17/)

In the example the loading gif is blocking for around 1-2 seconds while the image is being resized.

Anything I can do to avoid this? Or is this a bug?

**Comment by puzrin** [comment]
> Anything I can do to avoid this?

1. This package is wrapper around `pica`. Pica uses browser features progressively, to move into webworker as much as possible. But safary does not supports OffscreenCanvas for example. Some actions still happen in main thread, causing lags.
2. Note, this package is about resize quality first, not about "speed".
3. https://github.com/nodeca/pica/blob/master/demo/index.js#L22 - you can investigate debug messages to see what happens in you case.
