### ISSUE TITLE
Output is blank when running on mobile

### ISSUE THREAD

**Issue by iuliancmarcu** [nodeca/image-blob-reduce#45]
Hi, I have the following function that I am using to get a blob URL to use inside some `<img />` elements in the application:
```typescript
import ImageBlobReduce from 'image-blob-reduce';

export const resizeBlobImage = (file: Blob, size?: number): Promise<string> =>
    new ImageBlobReduce()
        .toBlob(file, {
            max: size ?? 1000,
        })
        .then(blob => URL.createObjectURL(blob));
```

I am using this to display previews of files selected by the user for upload.

Although this works perfectly on a desktop, the previews are blank when I run the application on Google Chrome on Android.

Has anyone else encountered this issue? Is there any potential fix that I can use?

**Comment by puzrin** [comment]
99.9% - no access permissions to canvas content, when HTML doc is used in the scope of local file system instead of a web domain. No ideas about fix - try to google this direction.

**Comment by iuliancmarcu** [comment]
@puzrin Thanks for taking out some of your time to reply! 

I suspected the same as you - having the canvas tainted and getting no result because of that - but the library works well when used in a desktop browser. Do you think it could be something else that causes the issue instead?

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/tree/master/demo - i had to embed image into pica demo for workaround. Don't remember details. May be this can help. Data URI images should be accessible.
