### ISSUE TITLE
How/where to configure filter

### ISSUE THREAD

**Issue by atomicrobokid** [nodeca/image-blob-reduce#46]
Hi,

I see that this uses Pica under the hood, how do i configure a different filter, i.e. `lanczos3` ?

TIA

**Comment by puzrin** [comment]
https://github.com/nodeca/image-blob-reduce#reexports

Pica is re-exported and can be configured to pass via options. Something like that:

```js
const ibr = require('image-blob-reduce')

const reducer = ibr({ pica: ibr.pica(your_options) })
```
