### ISSUE TITLE
Simple html example

### ISSUE THREAD

**Issue by plague69** [nodeca/image-blob-reduce#6]
Any chance of a simple example without all JS embedded into the index.js file?

eg. just the normal dist js used <script src="image-blob-reduce.min.js"></script>, all additional js in <script> inside index.html.

This would make it easier for people new to JS understand how to initialize and use the code, since example in readme currently uses require and that is not part of the package if you're using a browser and not NodeJS

**Comment by puzrin** [comment]
Just use `window['image-blob-reduce']`. IMO this is a basic programming question, not specific to this package. I have no plans for such tutorials.

But probably PR could be accepted (no any guarantees, until see diff).

**Comment by yanickrochon** [comment]
I agree with this issue, and it should not have been closed before actually being resolved. The example does nothing and looking at the source code is definitely _not_ helpful. Having a PR is irrelevant, this is not resolved, and the state of this issue should reflect it until a resolution is properly given.

**Comment by puzrin** [comment]
PRs are welcome. Mentoring and brainf**king - not.

**Comment by plague69** [comment]
Great library, thanks team for working on it. Managed to get it to work the way I need after digging through a few levels. (<input file> -> Resize -> JPG -> Ajax PUT)

I'll see if I have time to put it al into an example for PR

**Comment by puzrin** [comment]
> Question is, did you want an 'example' folder in Master, or example.html in "gh-pages"?

I have no personal preferences. My only criteria is "it should be easy to maintain"

**Comment by puzrin** [comment]
This is minimal working html snippet:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/image-blob-reduce@1.0.6/dist/image-blob-reduce.min.js"></script>
  </head>
  <body>
    <div><input id="uploader" type="file"></div>
    <div><img id="result"></div>
    <script>
      window.addEventListener('DOMContentLoaded', function () {
        document.getElementById('uploader').addEventListener('change', function () {
          var reducer = new (window.imageBlobReduce)();

          reducer
            .toBlob(
              this.files[0],
              { max: 200, unsharpAmount: 80, unsharpRadius: 0.6, unsharpThreshold: 2 }
            )
            .then(function (blob) {
              document.getElementById('result').src = URL.createObjectURL(blob);
            });
        });
      });
    </script>
  </body>
</html>
```

Global name now seems `window.imageBlobReduce`. Seems browserifier "camelified" it. Probably, need fix in net releases.

**Comment by plague69** [comment]
Thank you, that's perfect
