### ISSUE TITLE
Is Pica a requirement or is it bundled?

### ISSUE THREAD

**Issue by yanickrochon** [nodeca/image-blob-reduce#8]
I am hitten an error that seems to suggest `Pica` is not present. I see the module in my `node_modules`, but this code

```js
// file is an instance of File which is also an instance of Blob
imageReduce.toBlob(file, { max: 1000 })
    .then(blob => { 
        console.log("***BLOB", blob);
    });
```

yields this error

```
Uncaught (in promise) TypeError: image_blob_reduce__WEBPACK_IMPORTED_MODULE_5___default.a.toBlob is not a function
```

**Comment by puzrin** [comment]
`ImageBlobReduce` is class. Make sure you created instance via `new` or via `()` in `require(..)()`, as in examples. Also see web demo sources.
