### ISSUE TITLE
Add new image dimension instead of overriding the transform function

### ISSUE THREAD

**Issue by yanickrochon** [nodeca/image-blob-reduce#9]
This module should support resizing out of the box without needing to re-implement the entire `_transform` function. 

The usage could simply be :

```js
const reduce = require('image-blob-reduce')();

//...

// only specify width, causing height to be calculated proportionally
reduce
  .toBlob(image_blob, { max: 1000, width: 800 })
  .then(blob => { ... });

// only specify height, causing width to be calculated proportionally
reduce
  .toBlob(image_blob, { max: 1000, height: 500 })     // width calculated proportionally
  .then(blob => { ... });

// specifying both will cause the image to have custom scaling
reduce
  .toBlob(image_blob, { max: 1000, width: 800, height: 200 })
  .then(blob => { ... });
```

**Comment by puzrin** [comment]
Unfortunately, described options are not consistent. Because user may wish to resize image for cropping (restrict minimal possible size, 800x600 => 200x200). Your suggestion is obvious but has no good resolution at current moment (at least, i don't know).

IMO the only constructive thing, possible at current moment is to collect concreete use cases, then check how to land those into extra options.

**Comment by yanickrochon** [comment]
Well, for what's worth, the `max` option is quite non descriptive, and non consistent as well. Having `maxWidth` or `maxHeight` would've been a better option.

And, again, you're closing an issue without proper resolution! How can this project "collect concrete use cases" if the issues associated with the use cases are closed and buerried away so no one sees them?

Let the issues open so others see them and comment on them to provide more user input!

**Comment by puzrin** [comment]
If you have default permission to write to this tracker, that does not means you are welcome with any kind of naive comments. I'm not your free programmer. Just do a fork a stop wasting my time.
